baseURL = "https://www.cdc350723.cn/"
languageCode = "zh-CN"
defaultContentLanguage = "cn"

title = "光泽县疾控中心"
theme = "hugo-theme-learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
enableGitInfo = true

[params]
  editURL = "https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/"
  description = "Documentation for Hugo Learn Theme"
  author = "Mathieu Cornic"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Guangze CDC"
weight = 2
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/matcornic/hugo-theme-learn"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> Showcases"
url = "showcase"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Hugo Documentation"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30

[Languages.cn]
title = "光泽县疾控中心"
weight = 1
languageName = "Chinese"

[[Languages.cn.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Github 仓库"
identifier = "ds"
url = "https://github.com/matcornic/hugo-theme-learn"
weight = 10

[[Languages.cn.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> Vitrine"
url = "/showcase"
weight = 11

[[Languages.cn.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Hugo技术文档"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[Languages.cn.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> 制作人员"
url = "/credits"
weight = 30
